### PR TITLE
[21711] Update DataWriter/Reader `get_matched_publication/subscription...()` API tests

### PR DESCRIPTION
**Pull request by Mario-DL**
## Description

This PR updates DataWriter/Reader `get_matched_publication/subscirption...()` tests as result of API implementation:

* eProsima/Fast-DDS#5284

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- [X] Changes are API compatible. 
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by richiware — CHANGES_REQUESTED** [review]
Tests are failing.

**Comment by Mario-DL** [comment]
Tests were failing because we merged the implementation PR and the branch in `Fast DDS` is no longer available. We would need to manually run it.

**Comment by Mario-DL** [comment]
Manual CI run: 
[Fast DDS Python Ubuntu CI](https://github.com/eProsima/Fast-DDS-python/actions/workflows/ubuntu-ci.yml)
[Fast DDS Python Windows CI](https://github.com/eProsima/Fast-DDS-python/actions/workflows/windows-ci.yml)

**Comment by Mario-DL** [comment]
I am closing this since its implementation entails a behavior change and new majors are not planned for `2.x`

**Pull request closed without merging**
